# Configuration of data generator
t_window: 6
horizon: 1
feats_to_use:
    # Raw numeric features without aggregation
    raw_n: []
            #'txn_cnt', 'txn_amt', #'domestic_offline_amt_pct', 
#             'domestic_online_amt_pct', #'overseas_offline_amt_pct', 
#             'overseas_online_amt_pct', 
#             'card_1_txn_amt_pct', 
#             'card_2_txn_amt_pct', #'card_3_txn_amt_pct',
#             'card_4_txn_amt_pct', #'card_5_txn_amt_pct', 
#             'card_6_txn_amt_pct', #'card_7_txn_amt_pct', 
            #'card_8_txn_amt_pct', #'card_9_txn_amt_pct',
#             'card_10_txn_amt_pct', 
            #'card_11_txn_amt_pct', 
#             'card_12_txn_amt_pct', 
#             'card_13_txn_amt_pct', 
#             'card_14_txn_amt_pct', 
#             'card_other_txn_amt_pct', 
            #'slam']
    # Global switch for categorical features
    use_cat: False
    # If client attributes are taken into consideration
    use_cli_attrs: False
    # If client predicting vectors from TIFU-KNN are considered
    use_tifu_pred_vecs: True
    tifu:
        # Whether to use client vector or predicting vectors, the choices are
        # as follows:
        #     {'cli', 'pred'}
        scale: 'cli'
        t_lower_bound: 0   # The earliest time point to consider in purchasing
                           # map
        gp_size: 3
        decay_wt_g: 0.5
        decay_wt_b: 0.9
        alpha: 0.9
        sim_measure: 'cos'
        k: 100
        n_neighbor_candidates: 1000
    # If client identifiers are taken into consideration to help learn
    # the client-specific patterns (*need to clarify)
    use_chid: False
    # If chid is treated as a categorical feature
    chid_as_cat: False
    # If shop tags are taken into consideration to help learn the
    # shop_tag-specific patterns (*need to clarify)
    use_shop_tag: False